# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

flutter_application_path = '../AddFlutterDemo'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'AddFlutterToApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AddFlutterToApp

  pod 'AFNetworking'
  install_all_flutter_pods(flutter_application_path)
  

  target 'AddFlutterToAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AddFlutterToAppUITests' do
    # Pods for testing
  end

end
